version: "3.8"

services:
  chamado-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chamado-app
    entrypoint: sh /usr/local/bin/entrypoint.sh
    depends_on:
      chamado-db:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - chamado-network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: chamado-db
      DB_PORT: 3306
      DB_DATABASE: chamado
      DB_USERNAME: root
      DB_PASSWORD: root

  chamado-db:
    image: mysql:5.7
    container_name: chamado-db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: chamado
      MYSQL_ROOT_PASSWORD: root
    networks:
      - chamado-network

networks:
  chamado-network:
    driver: bridge

volumes:
  db_volume: {}